### ISSUE TITLE
[BUG] DogeCoinDark Linux precompiled package conflicts with newer miniupnpc

### ISSUE THREAD

**Issue by ShapeShifter499** [doged/dogedsource#1]
Hi,

The precompiled package for DogeCoinDark Linux found on the official page, http://dogecoindark.net/downloads/dogecoindark-qt.v.1.rar, needs to be recompiled with a newer miniupnpc (and maybe newer boost lib). Trying to run it on my system resulted in this error 

```
dogecoindark-qt: error while loading shared libraries: libminiupnpc.so.8: cannot open shared object file: No such file or directory
```

Seems my OS, Arch Linux, currently has miniupnpc 1.9.  Some folks may just stop trying to use DogeCoinDark if the precompiled version fails meaning the community loses more members and users of the coin.

Regards,
Lance

**Comment by doged** [comment]
do you mean the arch package?
https://aur4.archlinux.org/packages/dogecoindark-qt-git/

or do you mean the actual linux binary qt wallet?
http://dogecoindark.net/downloads/dogecoindark-qt.v.1.rar

**Comment by ShapeShifter499** [comment]
@doged I mean the binary qt, the same one you and I linked to.

EDIT: They now have switched the AUR3 to AUR4 to the old URL once again, please remove the '4' from the link that is on the official page.

**Comment by doged** [comment]
ah ok, just read this.

**Comment by doged** [comment]
its 4. i just checked. that link i posted above your comment works, 3 does not.
