### ISSUE TITLE
[BUG] DogeCoinDark GUI incorrectly shows coins as 'immature'

### ISSUE THREAD

**Issue by ShapeShifter499** [doged/dogedsource#2]
Hi,

The DogeCoinDark GUI incorrectly shows coins as 'immature' when they are not the product of mining. It does not correctly look for the "generated: true" variable on a transaction. The issue shows as follows.

![bvholfll](https://cloud.githubusercontent.com/assets/388665/9548190/f17d417c-4d53-11e5-9562-bd94fd702643.jpg)

Regards, Lance

**Comment by doged** [comment]
ok but they show up in balance after 6 confirms, correct?
